// <auto-generated />
namespace NMD1721050392.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Add_table_Person_student_Lecture : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_table_Person_student_Lecture));
        
        string IMigrationMetadata.Id
        {
            get { return "202110260650264_Add_table_Person_student_Lecture"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
